### ISSUE TITLE
thread 'main' panicked at src/prover.rs:154:66:

### ISSUE THREAD

**Issue by rigaz29** [nexus-xyz/nexus-cli#24]
```
Waiting for another program to prove...
thread 'main' panicked at src/prover.rs:154:66:
called Result::unwrap() on an Err value: Protocol(ResetWithoutClosingHandshake)
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

**Comment by collinjackson** [comment]
@rigaz29 we made some updates to error handling, are you still seeing this issue if you update? (i.e. run the curl command again)
